services:
  app:
    image: ghcr.io/ahmedlemine/foldercast:latest
    container_name: foldercast
    restart: unless-stopped

    ports:
      - "8123:80"

    environment:
      # Generate a new key at:
      # https://djecrety.ir/
      SECRET_KEY: "replace-with-your-own-secret-key"

      # Use '*' to allow any host or specify domains/IPs
      ALLOWED_HOSTS: "*"
      
      # Update to match the first part of 'posts:' above
      SERVER_PORT: "8123"
      
      # Update to match your server URL and port
      CSRF_TRUSTED_ORIGINS: "http://<your_server_ip>:8123"

      ADMIN_NAME: "your name"
      ADMIN_EMAIL: "your@email.com"
      
      # Optional
      TIME_ZONE: "UTC"

    volumes:
      # Folder containing your audio library
      - ./library:/app/library

      - static_volume:/app/static_cdn
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume:
