# Generated by Django 5.2.7 on 2025-11-04 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('artwork', models.URLField()),
                ('qr_code', models.URLField()),
                ('items_count', models.PositiveBigIntegerField(default=0)),
                ('last_generated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
